language: java

# This is essential lest the script is ignored and Travis just runs gradle.
install: true

script: ./.travis-build.sh

sudo: false

jdk:
  - openjdk7
# Not oraclejdk7 because it has little additional benefit over openjdk7.
#  - oraclejdk7
  - oraclejdk8


git:
  depth: 3
